mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"
gui:
  # Text to be displayed before the variable. No placeholders necessary
  reason: "&7Reason: &f"
  bannedBy: "&7Banned by: &f"
  bannedAt: "&7Banned at: &f"
  banExpiresAt: "&7Ban Expires At: &f"
  prematurelyBannedMessage: "&7Note: &fThis ban was prematurely lifted by the admins"
errorMessages:
  mustBePlayer: "You must be a player to execute this command!"
  noPlayerSpecified: "You must specify a player to ban!"
  noDurationGiven: "You must specify a duration for the ban!"
  noReasonGiven: "You must specify a reason for the ban!"
  invalidPlayer: "The player specified does not exist"